### PR TITLE
Fix pipelines configuration mismapping

### LINKED ISSUE #1091: DPL-879 [BUG] Fix configuration hierarchy mismapping
**Describe the bug**
Fix configuration hierarchy mismapping in the YAML config files used in message and sample-sheet generation.

**RT Ticket Number**
N/A

**To Reproduce**
Steps to reproduce the behaviour:
1. Create config:
    ```yml
    top:
      middle:
        bottom: 'leaf'
    ```
2. Access `top.bottom`

**Expected behaviour**
Returns error

**Actual behaviour**
Returns `leaf`

**Additional context**
Blocker for #1058

### PR DESCRIPTION
**Pull request by StephenHulme**
Closes #1091 

Identifies, documents, and fixes a bug impacting the generation of Configuration objects used in the generation of Messages and Sample Sheets.

For an explanation on how the fix works, see this [blog post](https://veerpalbrar.github.io/blog/2021/04/25/Questions-Answered-4-Singleton-Methods-in-Ruby).

#### Changes proposed in this pull request:

- Test version attribute independence
- Test heirachrary attribute independence
- Fix configuration mismapping

#### Instructions for Reviewers

_[All PRs] - Confirm PR template filled_  
_[Feature Branches] - Review code_  
_[Production Merges to `main`]_  
 &nbsp; &nbsp; \- _Check story numbers included_  
 &nbsp; &nbsp; \- _Check version_

### CODE REVIEW

File: spec/pipelines/configuration_spec.rb [hunk 1]
```diff
@@ -131,5 +133,29 @@
     it 'will raise an error if it is not a valid version' do
       expect { configuration.pipeline_c.sample_sheet.by_version('v30') }.to raise_error(Version::Error, 'Not a valid version')
     end
+
+    it 'will be able to access fields for a specific version' do
+      expect(configuration.pipeline_c.sample_sheet.by_version('v10').field_10).to eq('b')
+    end
+
+    it 'will not be able to access fields from another version' do
+      assert_raises NoMethodError do
```
Comment (BenTopping) [inline spec/pipelines/configuration_spec.rb:142]: `expect { configuration.pipeline_c.sample_sheet.by_version('v10').field_20 }.to raise_error(NoMethodError)`
Have you tried the above? I don't think i've come across assert_raises in rspec before. Feels more like a pytest style assertion.

File: app/pipelines/pipelines/configuration.rb [hunk 2]
```diff
@@ -44,7 +44,10 @@ def initialize(pipeline, children = {})
 
         children.each do |key, child|
           if child.instance_of?(ActiveSupport::HashWithIndifferentAccess)
-            create_instance_method(key) { Item.new(pipeline, child) }
+            unless respond_to?(key)
+              child_item = Item.new(pipeline, child)
+              create_instance_method(key) { child_item }
+            end
```
[the remark this answers is not in the document]
Comment (BenTopping) [reply app/pipelines/pipelines/configuration.rb:50]: Is this change still needed if we are using the `define_singleton_method`? If so, it would be worth bumping up the `respond_to?` to line 46 so we can remove the extra nested if.

File: app/pipelines/pipelines.rb [hunk 3]
```diff
@@ -29,7 +29,7 @@ module InstanceMethodCreator
     # @param key [String] the name of the method to be defined
     # @param block [Block] the body of the method to be defined
     def create_instance_method(key, &block)
-      self.class.send(:define_method, key, block)
+      define_singleton_method(key) { block.call }
```
[the remark this answers is not in the document]
Comment (BenTopping) [reply app/pipelines/pipelines.rb:32]: Nice one!

File: spec/pipelines/ont/message_spec.rb [hunk 4]
```diff
@@ -7,24 +7,23 @@
     create(:ont_min_know_version, name: 'v22', default: true)
   end
 
-  let(:config)            { Pipelines.configure(Pipelines.load_yaml) }
-  let(:pipeline_config)   { config.ont.message }
+  let(:configuration) { Pipelines.configure(Pipelines.load_yaml).ont.message }
```
Comment (BenTopping) [inline spec/pipelines/ont/message_spec.rb:10]: I would remove `.ont.message` from here or rename the variable to ont_message_config just to make it slightly clearer as 'configuration' is the high level class for the whole config.

File: spec/pipelines/pacbio/message_spec.rb [hunk 5]
```diff
@@ -4,7 +4,7 @@
 
 RSpec.describe 'PacBio', pacbio: true, type: :model do
   let(:timestamp) { Time.zone.parse('Mon, 08 Apr 2019 09:15:11 UTC +00:00') }
-  let(:pacbio_config) { Pipelines.configure(Pipelines.load_yaml).pacbio }
+  let(:configuration) { Pipelines.configure(Pipelines.load_yaml).pacbio.message }
```
Comment (BenTopping) [inline spec/pipelines/pacbio/message_spec.rb:7]: Same comment as above.

File: spec/pipelines/pipelines/configuration_spec.rb [hunk 6]
```diff
@@ -131,5 +138,23 @@
...
+    end
+
+    it 'will not be able to access fields from another version without by_version' do
+      expect(configuration.pipeline_c.sample_sheet.v20.field_20).to eq('c') # passes
+      expect { configuration.pipeline_c.sample_sheet.v10.field_20 }.to raise_error(NoMethodError) # field_20 returns 'c'
+    end
+
+    it 'will not be able to access fields from another version once another version has been loaded' do
+      expect(configuration.pipeline_c.sample_sheet.by_version('v20').field_20).to eq('c') # passes
+      expect { configuration.pipeline_c.sample_sheet.by_version('v10').field_20 }.to raise_error(NoMethodError) # field_20 returns 'c'
```
Comment (BenTopping) [inline spec/pipelines/pipelines/configuration_spec.rb:157]: Can remove these temporary comments now.

**Review by BenTopping — CHANGES_REQUESTED** [review]
Looks good, few minor comments. Well persevered as it was an ugly one!
